// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/meetings/[id]/live/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/meetings/[id]/live">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/meetings/[id]/live/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/meetings/[id]/summary/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/meetings/[id]/summary">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/meetings/[id]/summary/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/meetings/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/meetings/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/meetings/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/settings/agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/agent">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/settings/agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(app)/settings/voice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/voice">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/settings/voice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/internal/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/events">> = Specific
  const handler = {} as typeof import("../../../src/app/api/internal/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/internal/gateway/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/gateway/events">> = Specific
  const handler = {} as typeof import("../../../src/app/api/internal/gateway/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/meetings/[id]/finalize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meetings/[id]/finalize">> = Specific
  const handler = {} as typeof import("../../../src/app/api/meetings/[id]/finalize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/meetings/[id]/live/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meetings/[id]/live">> = Specific
  const handler = {} as typeof import("../../../src/app/api/meetings/[id]/live/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/meetings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meetings/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/meetings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/meetings/[id]/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meetings/[id]/start">> = Specific
  const handler = {} as typeof import("../../../src/app/api/meetings/[id]/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/meetings/[id]/stop/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meetings/[id]/stop">> = Specific
  const handler = {} as typeof import("../../../src/app/api/meetings/[id]/stop/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/meetings/[id]/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meetings/[id]/summary">> = Specific
  const handler = {} as typeof import("../../../src/app/api/meetings/[id]/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/meetings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/meetings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/meetings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/users/me/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/me/preferences">> = Specific
  const handler = {} as typeof import("../../../src/app/api/users/me/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/voices/[id]/finalize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voices/[id]/finalize">> = Specific
  const handler = {} as typeof import("../../../src/app/api/voices/[id]/finalize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/voices/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voices/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/voices/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/voices/[id]/sample/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voices/[id]/sample">> = Specific
  const handler = {} as typeof import("../../../src/app/api/voices/[id]/sample/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/voices/enroll/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voices/enroll">> = Specific
  const handler = {} as typeof import("../../../src/app/api/voices/enroll/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/voices/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voices/me">> = Specific
  const handler = {} as typeof import("../../../src/app/api/voices/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
